version: '3.9'

volumes:
  gws-code:
    external: true
    name: gws-code
  gws-db-data:
    external: true
    name: gws-db-data

services:
  gws-postgis:
    image: gplates/postgis
    networks:
      - gws-net
    hostname: gws-postgis
    volumes:
      - gws-db-data:/var/lib/postgresql/12/main
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD="this is not a real password! go away!"
    restart: on-failure
    healthcheck:
      test: "exit 0"

  gws:
    image: gplates/gws
    networks:
      - gws-net
    hostname: gws
    volumes:
      - gws-code:/gws
    ports:
      - 18000:80
    restart: on-failure
    healthcheck:
      test: curl --fail -s http://localhost:18000/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

networks:
  gws-net:
    external: true
