volumes:
  gws-code:
    external: true
    name: gws-code
  gplates-db-data:
    external: true
    name: gplates-db-data

services:
  gplates-postgis:
    extends:
      file: docker-compose.yml 
      service: gplates-postgis
    volumes:
      - gplates-db-data:/var/lib/postgresql/15/main

  gws:
    extends:
      file: docker-compose.yml
      service: gws
    volumes:
       - gws-code:/gws

  gplates-redis:
    extends:
      file: docker-compose.yml
      service: gplates-redis

networks:
  gplates-net:
    name: gplates-net
    driver: bridge
    external: true

