# This is for Michael Chin only... 
version: '3.9'

volumes:
  gws-code:
    external: true
    name: gws-code
  gws-db-data:
    external: true
    name: gws-db-data

services:
  gws-postgis:
    image: gplates/postgis
    networks:
      - gplates-net
    hostname: gws-postgis
    volumes:
      - gws-db-data:/var/lib/postgresql/15/main
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=gplates
    restart: on-failure
    healthcheck:
      test: pg_isready -U gplates -d gplates
      interval: 1m30s
      timeout: 10s
      retries: 3

  gws:
    image: gplates/gws
    networks:
      - gplates-net
    hostname: gws
    depends_on:
      - gws-postgis
      - gws-redis
    volumes:
      - gws-code:/gws
    ports:
      - 18000:80
    environment:
      - DB_PASSWORD=zaq12wsx
    restart: on-failure
    healthcheck:
      test: curl --fail -s "http://localhost:80/raster/query?lon=128.86&lat=-12.42&raster_name=crustal_thickness" || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
  
  gws-redis:
    image: redis
    networks:
      - gplates-net
    hostname: gws-redis
    restart: on-failure
    healthcheck:
      test: redis-cli -h gws-redis ping  
      interval: 1m30s
      timeout: 10s
      retries: 3


networks:
  gplates-net:
    driver: bridge
