version: '3.9'

volumes:
  gws-code:
    external: true
    name: gws-code
  gws-db-data:
    external: true
    name: gws-db-data-new

services:
  gws-postgis:
    image: gplates/postgis
    networks:
      - gws-net
    hostname: gws-postgis
    volumes:
      - gws-db-data:/var/lib/postgresql/15/main
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD="this is not a real password! go away!"
    restart: on-failure
    healthcheck:
      test: "exit 0"

  gws:
    image: gplates/gws
    networks:
      - gws-net
    hostname: gws
    depends_on:
      - gws-postgis
      - gws-redis
    volumes:
      - gws-code:/gws
    ports:
      - 18000:80
    restart: on-failure
    healthcheck:
      test: curl --fail -s http://localhost:18000/raster/query?lon=128.86&lat=-12.42&raster_name=crustal_thickness || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
  
  redis:
    image: redis
    networks:
      - gws-net
    hostname: gws-redis
    restart: on-failure
    healthcheck:
      test: docker run -it --network gws-net --rm redis redis-cli -h gws-redis ping  


networks:
  gws-net:
    external: true
