#
# docker build -f docker/Dockerfile-postgis -t gplates/postgis .
#

FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Australia

RUN apt-get update
RUN apt-get install -y postgresql postgresql-contrib wget

#install postgis
RUN apt -y install gnupg2
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
RUN apt-get install -y lsb-release
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" | tee  /etc/apt/sources.list.d/pgdg.list
RUN apt update
RUN apt install -y  postgis postgresql-12-postgis-3

#initialize DB
ADD docker/init-db.sh /workspace/
ADD docker/create-gws-db.sql /workspace/
RUN chmod +x /workspace/init-db.sh
USER postgres
RUN cd /workspace/ && ./init-db.sh
USER root

#update postgres configuration file 
ADD docker/postgresql.conf /etc/postgresql/12/main/
ADD docker/pg_hba.conf /etc/postgresql/12/main/
RUN chown postgres:postgres /etc/postgresql/12/main/*

# Add Tini
ENV TINI_VERSION v0.9.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
ENTRYPOINT ["/tini", "--"]
#CMD ["/etc/init.d/postgresql start", "top"]
CMD ["sh", "-c", "/etc/init.d/postgresql start ; tail -f /dev/null"]
# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

EXPOSE 80

