version: '3.9'

services:
  gws-postgis:
    image: gplates/postgis
    hostname: gws-postgis
    networks:
      - gplates-net
    restart: on-failure
    healthcheck:
      test: pg_isready -U gplates -d gplates
      interval: 1m30s
      timeout: 10s
      retries: 3

  gws:
    image: gplates/gws
    hostname: gws
    networks:
      - gplates-net
    depends_on:
      - gws-postgis
      - gws-redis
    ports:
      - 18000:80
    restart: on-failure
    healthcheck:
      test: curl --fail -s "http://localhost:80/raster/query?lon=128.86&lat=-12.42&raster_name=crustal_thickness" || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
  
  gws-redis:
    image: redis
    hostname: gws-redis
    networks:
      - gplates-net
    restart: unless-stopped
    healthcheck:
      test: redis-cli -h gws-redis ping  
      interval: 1m30s
      timeout: 10s
      retries: 3

networks:
  gplates-net:
    driver: bridge

