name: Push Docker latest and test Docker Compose

on:
  release:
    types: [published]
#on:
#  push:
#    branches: 
#      - dev

jobs:
  push-docker-latest:
    runs-on: ubuntu-latest

    steps:
      -
        name: Push docker latest
        run: |
            docker buildx imagetools create -t gplates/postgis:latest gplates/postgis:amd64-${{ github.event.release.tag_name }} gplates/postgis:arm64-${{ github.event.release.tag_name }}
            docker buildx imagetools create -t gplates/gws:latest gplates/gws:amd64-${{ github.event.release.tag_name }} gplates/gws:arm64-${{ github.event.release.tag_name }}
    
  test-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Check out repository code
        uses: actions/checkout@v4
      -
        name: Start Docker compose
        run: |   
          cd docker
          docker-compose up -d
      - 
        name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash
      -  
        name: Check Docker compose
        if: always()
        run: |
           docker ps
           docker network ls
           docker inspect docker_gws_1 -f "{{json .NetworkSettings.Networks }}"
           wget http://localhost:18000
           curl --fail -s "http://localhost:18000/raster/query?lon=128.86&lat=-12.42&raster_name=crustal_thickness" || exit 1
           

          

