name: release test

on:
  release:
    types: [published]

jobs:
  push-docker-latest:
    runs-on: ubuntu-latest

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Push docker latest
        run: |
            docker buildx imagetools create -t gplates/postgis:latest gplates/postgis:amd64-${{ github.event.release.tag_name }} gplates/postgis:arm64-${{ github.event.release.tag_name }}
            docker buildx imagetools create -t gplates/gws:latest gplates/gws:amd64-${{ github.event.release.tag_name }} gplates/gws:arm64-${{ github.event.release.tag_name }}
            docker buildx imagetools create -t ghcr.io/gplates/postgis:latest ghcr.io/gplates/postgis:amd64-${{ github.event.release.tag_name }} ghcr.io/gplates/postgis:arm64-${{ github.event.release.tag_name }}
            docker buildx imagetools create -t ghcr.io/gplates/gws:latest ghcr.io/gplates/gws:amd64-${{ github.event.release.tag_name }} ghcr.io/gplates/gws:arm64-${{ github.event.release.tag_name }}
            
  test-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Check out repository code
        uses: actions/checkout@v4
      -
        name: Start Docker compose
        run: |   
          cd docker
          docker network create --driver bridge gplates-net
          docker compose -f docker-compose.yml up -d
      - 
        name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash
      -  
        name: Check Docker compose
        if: always()
        run: |
           docker ps
           docker network ls
           docker inspect docker_gws_1 -f "{{json .NetworkSettings.Networks }}"
           wget http://localhost:18000/reconstruct/reconstruct_points/?lons=95,142&lats=54,-33&time=140
           curl --fail -s "http://localhost:18000/raster/query?lon=128.86&lat=-12.42&raster_name=crustal_thickness" || exit 1
           

          

